TASKMANAGER.WEB/Controllers/ConstructionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TaskManager.Application.Interfaces;
using TaskManager.Application.ViewModels.Car;
using TaskManager.Application.ViewModels.Construction;

namespace TASKMANAGER.WEB.Controllers
{
    public class ConstructionController : Controller
    {
        private readonly IConstructionService _cstr;
        private readonly ICarService _carServ;

        public ConstructionController(IConstructionService cstr, ICarService carServ)
        {
            _carServ = carServ;
            _cstr = cstr;
        }
        [HttpGet]
        public IActionResult Index()
        {

            var model = _cstr.GetAllConstruction("");
            return View(model);

        }
        [HttpPost]
        public IActionResult Index(string searchString)
        {
            if (searchString is null)
            {
                searchString = String.Empty;
            }
            var model = _cstr.GetAllConstruction(searchString);
            return View(model);
        }

        [HttpGet]
        public IActionResult AddConstruction()
        {
            var model = new AddConstructionVm();
            model.Date = DateTime.Now;


            return View(model);
        }
        [HttpPost]
        public IActionResult AddConstruction(AddConstructionVm model)
        {
            _cstr.AddConstruction(model);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            var model = _cstr.GetConstruction(id);
            return View(model);
        }
        //[HttpPost]
        //public IActionResult Details(DetailsConstructionVm model)
        //{
        //    _cstr.UpdateConstruction(model);
        //    return RedirectToAction("Index");
        //}



        [HttpGet]
        public IActionResult Clone(int id)
        {
            _cstr.Copy(id);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult AddEmployeeToConstruction(int id)
        {
            var model = _cstr.AddEmployeeToConstructionView(id);
            return View(model);
        }
        [HttpPost]
        public IActionResult AddEmployeeToConstruction(AddEmployeeToConstructionList model)
        {
            _cstr.AddEmployeeToConstruction(model);
            return RedirectToAction("Details" , new{id = model.ConstructionId } );
        }
        public IActionResult RemoveEmployeeFromConstruction(int empId, int consId)
        {
            _cstr.RemoveEmployeeFromConstruction(empId, consId);
            return RedirectToAction("Details", new { id = consId });
        }
        [HttpGet]
        public IActionResult AddItemToConstruction(int id)
        {
            var model = _cstr.AddItemToConstructionView(id);
            return View(model);
        }
        [HttpPost]
        public IActionResult AddItemToConstruction(AddItemToConstructionListVm model)
        {
            _cstr.AddItemToConstruction(model);
            return RedirectToAction("Details", new { id = model.ConstructionId });
        }




        //----------------------------------------------------------------CARS-------------------------------------------------------------------//
        //----------------------------------------------------------------CARS-------------------------------------------------------------------//
        [HttpGet]
        public IActionResult Cars()
        {

            var model = _carServ.GetAllCars("");
            return View(model);

        }
        [HttpPost]
        public IActionResult Cars(string searchString)
        {
            if (searchString is null)
            {
                searchString = String.Empty;
            }
            var model = _carServ.GetAllCars(searchString);
            return View(model);
        }
        [HttpGet]
        public IActionResult Addcars()
        {

            return View(new AddCarVm());

        }
        [HttpPost]
        public IActionResult Addcars(AddCarVm models)

        {
            _carServ.AddCar(models);
            return RedirectToAction("Cars");

        }

    }
}

TASKMANAGER.WEB/Controllers/ErrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using TaskManager.Application.Interfaces;
using TaskManager.Application.ViewModels.Errand;
using TaskManager.Domain.Interfaces;

namespace TASKMANAGER.WEB.Controllers
{
    public class ErrandController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IErrandServices _errServ;

        public ErrandController(IErrandServices errServ, IMapper mapper)
        {
            _errServ = errServ;
            _mapper = mapper;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var errands = _errServ.GetAllErand("");
            return View(errands);
        }
        [HttpPost]
        public IActionResult Index(string searchString)
        {
            if (searchString is null)
            {
                searchString = String.Empty;
            }
            var errands = _errServ.GetAllErand(searchString);
            return View(errands);
        }
        [HttpGet]
        public IActionResult AddErrand()
        {
            var model = new AddErrandVm();
            model.Categories = _errServ.GetErrandCategory().ToList();
            return View(model);
        }
        [HttpPost]
        public IActionResult AddErrand(TaskManager.Application.ViewModels.Errand.AddErrandVm model)
        {
            var id = _errServ.AddErrand(model);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var errand = _errServ.GetErandToEdit(id);
            errand.Categories = _errServ.GetErrandCategory().ToList();
            errand.Statuses = _errServ.GetErrandStatus().ToList();
            return View(errand);
        }
        [HttpPost]
        public IActionResult Edit(ErrandVm model)
        {
            _errServ.UpdateErrand(model);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            _errServ.DeleteErrand(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult AddCategory()
        {
            return View(new CategoryVm());
        }
        [HttpPost]
        public IActionResult AddCategory(CategoryVm model)
        {
            _errServ.AddNewCategory(model);
            return RedirectToAction("Index");
        }
  
        public IActionResult Clone(int id)
        {
            _errServ.CopyErrand(id);
            return RedirectToAction("Index");
        }
    }
}

TASKMANAGER.WEB/Views/Construction/AddConstruction.cshtml
@model TaskManager.Application.ViewModels.Construction.AddConstructionVm

@{
    ViewData["Title"] = "AddConstruction";
}

<h1>Dodaj Budowe</h1>


<hr />
<div class="row justify-content-center">
    <div class="col-md-4 ">
        <form asp-action="AddConstruction">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
        <label asp-for="Id" class="control-label"></label>*@
            <input type="hidden" asp-for="Id" class="form-control" />
            @*<span asp-validation-for="Id" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label">Nazwa</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Week" class="control-label">Tydzień</label>
                <input asp-for="Week" class="form-control" />
                <span asp-validation-for="Week" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label">Data</label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddressLine1" class="control-label">Adres</label>
                <input asp-for="AddressLine1" class="form-control" />
                <span asp-validation-for="AddressLine1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label">Miasto</label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label">Państwo</label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCode" class="control-label">Kod Pocztowy</label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Bufor" /> @Html.DisplayNameFor(model => model.Bufor)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Gotowe" class="btn btn-success" />
                <a class="btn btn-danger" style="height:38px" ,"width: 100px;" asp-action="Index" asp-controller="Construction">Anuluj </a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TASKMANAGER.WEB/Views/Construction/AddEmployeeToConstruction.cshtml
@model TaskManager.Application.ViewModels.Construction.AddEmployeeToConstructionList

@{
    ViewData["Title"] = "AddEmployeeToConstruction";
}

<h1>AddEmployeeToConstruction</h1>

<form asp-action="AddEmployeeToConstruction">
    <table class="table">
        <thead>
            <tr>
                <th>
                    Imię
                </th>
                <th>
                    Nazwisko
                </th>
                <th>
                    Pozycja
                </th>
                <th>
                    <center>Zaznacz</center>
                </th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Employee.Count; i++)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Model.Employee[i].FirstName, new { @class = "form-control", @readonly = "readonly" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.Employee[i].LastName, new { @class = "form-control", @readonly = "readonly" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.Employee[i].Position, new { @class = "form-control", @readonly = "readonly" })
                    </td>
                    <td>
                        <center> <input class="form-check-input" asp-for="Employee[i].Check" /></center>
                    </td>

                </tr>

                @Html.HiddenFor(modelItem => Model.ConstructionId)
                @Html.HiddenFor(modelItem => Model.EmployeeId)
                @Html.HiddenFor(modelItem => Model.Employee[i].Id, new { @class = "form-control", @readonly = "readonly" })

            }

        </tbody>
    </table>
    <div class="form-group">
        <input type="submit" value="Dodaj" class="btn btn-primary" id="save" />
    </div>
</form>

TASKMANAGER.WEB/Views/Construction/AddItemToConstruction.cshtml
@model TaskManager.Application.ViewModels.Construction.AddItemToConstructionListVm

@{
    ViewData["Title"] = "AddItemToConstruction";
}

<h1>AddEmployeeToConstruction</h1>

<form asp-action="AddItemToConstruction">
    <table class="table">
        <thead>
            <tr>
                <th>
                    Nazwa
                </th>
                <th>
                    Ilośc
                </th>
                <th>
                    <center>Zaznacz</center>
                </th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Items.Count; i++)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Model.Items[i].Name, new { @class = "form-control", @readonly = "readonly" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.Items[i].Qantity, new { @class = "form-control", @readonly = "readonly" })
                    </td>

                    <td>
                        <center> <input class="form-check-input" asp-for="Items[i].Check" /></center>
                    </td>

                </tr>

                @Html.HiddenFor(modelItem => Model.ConstructionId)
                @Html.HiddenFor(modelItem => Model.ItemId)
                @Html.HiddenFor(modelItem => Model.Items[i].Id, new { @class = "form-control", @readonly = "readonly" })

            }

        </tbody>
    </table>
    <div class="form-group">
        <input type="submit" value="Dodaj" class="btn btn-primary" id="save" />
    </div>
</form>

TASKMANAGER.WEB/Views/Construction/Addcars.cshtml
@model TaskManager.Application.ViewModels.Car.AddCarVm

@{
    ViewData["Title"] = "Addcars";
}

<h1>Dodaj Pojazd</h1>


<hr />

<div class="row justify-content-center">
    <div class="col-md-4">
        <form asp-action="Addcars">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" class="form-control" />
            <div class="form-group">
                <label asp-for="Brand" class="control-label">Marka</label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label">Model</label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VehicleRegistrationNumber" class="control-label">Numer Rejestracyjny</label>
                <input asp-for="VehicleRegistrationNumber" class="form-control" />
                <span asp-validation-for="VehicleRegistrationNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Seats" class="control-label">Liczba Miejsc</label>
                <input asp-for="Seats" class="form-control" />
                <span asp-validation-for="Seats" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label">Rok Pojazdu</label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarInsurance" class="control-label">Ubezpieczenie</label>
                <input asp-for="CarInsurance" class="form-control" />
                <span asp-validation-for="CarInsurance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarReview" class="control-label">Przegląd</label>
                <input asp-for="CarReview" class="form-control" />
                <span asp-validation-for="CarReview" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tires" class="control-label">Opony</label>
                <input asp-for="Tires" class="form-control" />
                <span asp-validation-for="Tires" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Gotowe" class="btn btn-success" />
                <a class="btn btn-danger" style="height:38px" ,"width: 100px;" asp-action="Index" asp-controller="Construction">Anuluj </a>
            </div>
        </form>
    </div>
</div>


    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

TASKMANAGER.WEB/Views/Construction/Cars.cshtml
@model TaskManager.Application.ViewModels.Car.CarsListVm

@{
    ViewData["Title"] = "Cars";
}

<h1>Lista Pojazdów</h1>

<form>
    <div class="">
        <input type="text" asp-for="SearchString" name="searchString" id="searchString" />
        <input type="submit" value="Wyszukaj" class="btn btn-success" />
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Marka
                </th>
                <th>
                    Model
                </th>
                <th>
                    Nr Rejestracyjny
                </th>
                <th>
                    Liczba miejsc
                </th>
                <th>
                    Akcje
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Cars)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Brand)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Model)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VehicleRegistrationNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Seats)
                    </td>
                    <td>
                        <a class="btn btn-success" style="height:40px" ,"width: 100px;" href="@Url.Action("", "Errand", new { id = item.Id })">Akcja</a>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</form>

TASKMANAGER.WEB/Views/Construction/Details.cshtml
@model TaskManager.Application.ViewModels.Construction.DetailsConstructionVm

@{
    ViewData["Title"] = "Details";
}


<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Details" class="wraper">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="detailsconstruction_construction">
                <input type="hidden" asp-for="Id" class="form-control" />

                <div class="form-group">
                    <label asp-for="Name" class="control-label">Nazwa</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Week" class="control-label">Tydzień</label>
                    <input asp-for="Week" class="form-control" />
                    <span asp-validation-for="Week" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Date" class="control-label">Data</label>
                    <input type="date" asp-for="Date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="AddressLine1" class="control-label">Adres</label>
                    <input asp-for="AddressLine1" class="form-control" />
                    <span asp-validation-for="AddressLine1" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="City" class="control-label">Miasto</label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Country" class="control-label">Państwo</label>
                    <input asp-for="Country" class="form-control" />
                    <span asp-validation-for="Country" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ZipCode" class="control-label">Kod Pocztowy</label>
                    <input asp-for="ZipCode" class="form-control" />
                    <span asp-validation-for="ZipCode" class="text-danger"></span>
                </div>
            </div>
            <div class="detailsconstruction_employee" >
                <div style=" height: 300px; width: 500px; overflow: auto;">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    Imię
                                </th>
                                <th>
                                    Nazwisko
                                </th>
                                <th>
                                    <a class="const_add_emp" href="@Url.Action("AddEmployeeToConstruction", "Construction",new { id = Model.Id }) "> <img src="~/css/list-add.png"></a>
                                    @*<a class="const_add_emp" asp-action="AddEmployeeToConstruction" asp-controller="Construction"> <img src="~/css/list-add.png"></a>*@
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Employee)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FirstName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.LastName)
                                    </td>
                                    <td>
                                        <a class="const_delete_emp" href="@Url.Action("RemoveEmployeeFromConstruction", "Construction", new { empId = item.Id, consId =Model.Id }) ">
                                            <img src="~/css/edit-delete.png">
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    </div>
                        <div style=" height: 300px; width: 500px; overflow: auto;">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>
                                            Nazwa
                                        </th>
                                        <th>
                                            Ilość
                                        </th>
                                        <th>
                                            <a class="const_add_emp" href="@Url.Action("AddItemToConstruction", "Construction",new { id = Model.Id }) "> <img src="~/css/list-add.png"></a>
                                            @*<a class="const_add_emp" asp-action="AddEmployeeToConstruction" asp-controller="Construction"> <img src="~/css/list-add.png"></a>*@
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.Items)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Name)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Qantity))
                                            </td>
                                            <td>
                                                <a class="const_delete_emp" href="@Url.Action("RemoveEmployeeFromConstruction", "Construction", new { itemId = item.Id, consId =Model.Id }) ">
                                                    <img src="~/css/edit-delete.png">
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>

                        </div>
                    </div>



                    



                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Bufor" /> @Html.DisplayNameFor(model => model.Bufor)
                        </label>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Gotowe" class="btn btn-success" />
                        <a class="btn btn-danger" style="height:38px" ,"width: 100px;" asp-action="Index" asp-controller="Construction">Anuluj </a>
                    </div>
</form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TASKMANAGER.WEB/Views/Construction/Index.cshtml
@model TaskManager.Application.ViewModels.Construction.ConstructionListVm

@{
    ViewData["Title"] = "Index";
}

<h1>Budowy</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                Nazwa
            </th>
            <th>
                Adres
            </th>
            <th>
                Data Wyjazdu
            </th>
            <th>
                Akcja
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Constructions)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AddressLine1)
                </td>
                <td>
                    @Convert.ToString(string.Format("{0:dd/MM/yyyy}", item.Date))
                </td>
                <td>
                    <a class="btn btn-info" style="height:40px , " width:100px" href="@Url.Action("Details", "Construction", new { id = item.Id })">Info</a>
                    <a class="btn btn-warning" style="height:40px , " width:100px" href="@Url.Action("Clone", "Construction", new { id = item.Id })">Klonuj</a>
                </td>
            </tr>
        }



            
    </tbody>
</table>