TASKMANAGER.WEB/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TaskManager.Application.Interfaces;
using TaskManager.Application.ViewModels.Employee;

namespace TASKMANAGER.WEB.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _empServ;


        public EmployeeController(IEmployeeService empServ)
        {
            _empServ = empServ;

        }
        [HttpGet]
        public IActionResult Index()
        {
            var model = _empServ.GetAllEmployee("");
            return View(model);
        }
        [HttpPost]
        public IActionResult Index(string searchString)
        {
            if (searchString is null)
            {
                searchString = String.Empty;
            }
            var model = _empServ.GetAllEmployee(searchString);
            return View(model);
        }
        [HttpGet]
        public IActionResult AddEmployee()
        {
            return View(new AddEmployeeVm());
        }
        [HttpPost]
        public IActionResult AddEmployee(AddEmployeeVm model)
        {
            var id = _empServ.AddEmploye(model);
            return RedirectToAction("Index");
        }
        public IActionResult DeleteEmployee(int id)
        {
            _empServ.DeleteEmployee(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditEmployee(int id)
        {
            var model = _empServ.GetEmployee(id);
            return View(model);
        }
        [HttpPost]
        public IActionResult EditEmployee(AddEmployeeVm model)
        {
            _empServ.UpdateEmployee(model);
            return RedirectToAction("Index");
        }
        public IActionResult Export()
        {
   
            _empServ.ExportEmployee();
            return RedirectToAction("Index");
        }
        public IActionResult Import()
        {
            _empServ.ImportEmployee();
            return RedirectToAction("Index");
        }



    }
}

TASKMANAGER.WEB/Controllers/ErrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using TaskManager.Application.Interfaces;
using TaskManager.Application.ViewModels.Errand;
using TaskManager.Domain.Interfaces;

namespace TASKMANAGER.WEB.Controllers
{
    public class ErrandController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IErrandServices _errServ;

        public ErrandController(IErrandServices errServ, IMapper mapper)
        {
            _errServ = errServ;
            _mapper = mapper;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var errands = _errServ.GetAllErand("");
            return View(errands);
        }
        [HttpPost]
        public IActionResult Index(string searchString)
        {
            if (searchString is null)
            {
                searchString = String.Empty;
            }
            var errands = _errServ.GetAllErand(searchString);
            return View(errands);
        }
        [HttpGet]
        public IActionResult AddErrand()
        {
            var model = new AddErrandVm();
            model.Categories = _errServ.GetErrandCategory().ToList();
            return View(model);
        }
        [HttpPost]
        public IActionResult AddErrand(TaskManager.Application.ViewModels.Errand.AddErrandVm model)
        {
            var id = _errServ.AddErrand(model);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var errand = _errServ.GetErandToEdit(id);
            errand.Categories = _errServ.GetErrandCategory().ToList();
            errand.Statuses = _errServ.GetErrandStatus().ToList();
            return View(errand);
        }
        [HttpPost]
        public IActionResult Edit(ErrandVm model)
        {
            _errServ.UpdateErrand(model);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            _errServ.DeleteErrand(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult AddCategory()
        {
            return View(new CategoryVm());
        }
        [HttpPost]
        public IActionResult AddCategory(CategoryVm model)
        {
            _errServ.AddNewCategory(model);
            return RedirectToAction("Index");
        }
  
        public IActionResult Clone(int id)
        {
            _errServ.CopyErrand(id);
            return RedirectToAction("Index");
        }
    }
}

TASKMANAGER.WEB/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TaskManager.Application.Interfaces;
using TaskManager.Application.ViewModels.Errand;
using TaskManager.Application.ViewModels.User;

namespace TASKMANAGER.WEB.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IErrandServices _errService;

        public UserController(IUserService userService , IErrandServices errandServices)
        {
            _userService = userService;
            _errService = errandServices;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var model = _userService.GetAllUser();
            return View(model);
        }
        public IActionResult Delete(string id)
        {
            _userService.DeleteUser(id);
            return RedirectToAction("Index");
        }

        public IActionResult MyErrands(string id)
        {
            var tasks = _userService.ViewTasks(id);
            return View(tasks);
        }


        [HttpGet]
        public IActionResult AddErrandtoUser(string id)
        {
            var model = _errService.GetUserForAddErrand(id);
            return View(model);
        }
        [HttpPost]
        public IActionResult AddErrandtoUser(ErrandListForAddToUserVm model)
        {
            if (ModelState.IsValid)
            { 
            try
            {
                _errService.AddErrandToUser(model);
                
            }
            catch(Exception ex)
            {
                return View(ex.Message);
            }
            }
            ModelState.AddModelError("", "Error1");
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Details(string id)
        {
            var model = _userService.GetUser(id);
            return View(model);
        }
        [HttpPost]
        public IActionResult Details(UserVm model)
        {
            _userService.UpdateUser(model);
            return RedirectToAction("Index");

        }
    }
}

TASKMANAGER.WEB/Controllers/WarehouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TaskManager.Application.Interfaces;
using TaskManager.Application.ViewModels.Warehouse;

namespace TASKMANAGER.WEB.Controllers
{
    public class WarehouseController : Controller
    {
        private readonly IWarehouseService _warService;

        public WarehouseController(IWarehouseService warService)
        {
            _warService = warService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = _warService.GetAllItems("");
            return View(model);
        }
        [HttpPost]
        public IActionResult Index(string searchString)
        {
            if (searchString is null)
            {
                searchString = String.Empty;
            }
            var items = _warService.GetAllItems(searchString);
            return View(items);
        }
        [HttpGet]
        public IActionResult AddItem()
        {
            var model = new AddItemVm();
            return View(model);
        }
        [HttpPost]
        public IActionResult AddItem(AddItemVm model)
        {
            _warService.AddItems(model);
            return RedirectToAction("Index");
        }
    }
}

TASKMANAGER.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TASKMANAGER.WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/css/HSILogo.jpg" style="width:80px; height:35px; border-radius:4px"> </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <div class="btn-group">
                                <button mar type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                    Użytkownicy
                                </button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="User" asp-action="Index">Lista </a>
                                </div>
                            </div>
                        </li>

                        <li class="nav-item">
                            <div class="btn-group">
                                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                    Zadania
                                </button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Errand" asp-action="Index">Lista Zadań</a>
                                    <a class="dropdown-item" asp-controller="Errand" asp-action="AddErrand">Dodaj Zadanie</a>
                                    <a class="dropdown-item" asp-controller="Errand" asp-action="AddCategory">Dodaj Kategorie</a>
                                </div>
                            </div>
                        </li>

                        <li class="nav-item">
                            <div class="btn-group">
                                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                    Pracownicy
                                </button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Employee" asp-action="Index">Lista Pracowników</a>
                                    <a class="dropdown-item" asp-controller="Employee" asp-action="AddEmployee">Dodaj Pracownika</a>
                                </div>
                            </div>
                        </li>


                        <li class="nav-item">
                            <div class="btn-group">
                                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                    Budowy
                                </button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Construction" asp-action="Index">Lista Budów</a>
                                    <a class="dropdown-item" asp-controller="Construction" asp-action="AddConstruction">Dodaj Budowe</a>
                                </div>
                            </div>
                        </li>

                        <li class="nav-item">
                            <div class="btn-group">
                                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                    Pojazdy
                                </button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Construction" asp-action="Cars">Lista Pojazdów</a>
                                    <a class="dropdown-item" asp-controller="Construction" asp-action="Addcars">Dodaj Pojazd</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="btn-group">
                                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                    Magazyn
                                </button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Warehouse" asp-action="Index">Lista</a>
                                    <a class="dropdown-item" asp-controller="Warehouse" asp-action="AddItem">DodajTowar</a>
                                </div>
                            </div>
                        </li>



                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TASKMANAGER.WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>